apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  redis-host: "redis-master.default.svc.cluster.local"
  kafka-brokers: "kafka-0.kafka.default.svc.cluster.local:9092,kafka-1.kafka.default.svc.cluster.local:9092,kafka-2.kafka.default.svc.cluster.local:9092"
